name: attachmentAV Malware Scanner
description: Scan files for malware and viruses using the attachmentAV API

inputs:
  local-file-path:
    description: Path to local file in the repository to scan - supports up to 100MB (mutually exclusive with artifact-id and release-asset-id)
    required: false
  artifact-id:
    description: GitHub Actions artifact ID to scan (mutually exclusive with local-file-path and release-asset-id)
    required: false
  release-asset-id:
    description: GitHub release asset ID to scan (mutually exclusive with local-file-path and artifact-id)
    required: false
  api-endpoint:
    description: attachmentAV API endpoint
    required: false
    default: 'https://eu.developer.attachmentav.com'
  api-key:
    description: attachmentAV API key (use secrets)
    required: true
  token:
    description: GitHub token or personal access token (PAT) - required for artifacts, local files >10MB and releases of private repositories (forwarded to attachmentAV for download authentication)
    required: false
  timeout:
    description: Timeout in seconds for async polling. Max 1 hour, min 1 second.
    required: false
    default: '300'
  polling-interval:
    description: Polling interval in seconds for async scans. Max 1 hour, min 1 second.
    required: false
    default: '5'
  fail-on-infected:
    description: Whether to fail the action if malware is detected
    required: false
    default: 'true'

outputs:
  status:
    description: Scan result status (clean/infected/no)
  finding:
    description: Malware type, not set if status is 'clean'
  file-size:
    description: Size of scanned file in bytes, not set if scanning failed
  real-file-type:
    description: Detected file type, not set if scanning failed

runs:
  using: node24
  main: dist/index.mjs
